import homeDesign from './home-design.json';

export interface SavedPost {
  /** Instagram shortcode, also the thumbnail filename. */
  id: string;
  url: string;
  kind: 'post' | 'reel';
  username: string;
  name: string;
  /** YYYY-MM-DD the post was saved, when the export knows it. */
  savedAt: string | null;
  /** Key of one of the collection's buckets. Hand-editable in the JSON. */
  bucket: string | null;
  /** Whether public/saved/<slug>/<id>.webp exists. */
  thumb: boolean;
  /** Set to true in the JSON to keep a post off the page. */
  hidden?: boolean;
}

export interface SavedCollection {
  slug: string;
  title: string;
  description: string;
  lede: string;
  /** Filter chips, in display order. */
  buckets: { key: string; label: string }[];
  posts: SavedPost[];
}

/** Tiles shown per filter before "Show more". */
export const PAGE_SIZE = 30;

// Each collection's JSON is generated by scripts/import-instagram-saved.mjs,
// newest save first.
export const savedCollections: SavedCollection[] = [
  {
    slug: 'home-design',
    title: 'Home Design',
    description: 'Rooms, houses, and furniture Justin Nguyễn has saved on Instagram over the years.',
    lede: "Rooms, houses, and furniture I've saved on Instagram over the years. Every photo belongs to the person credited on it. Click one to see the original post.",
    buckets: [
      { key: 'living', label: 'Living spaces' },
      { key: 'kitchen', label: 'Kitchens & dining' },
      { key: 'bedroom', label: 'Bedrooms' },
      { key: 'bath', label: 'Bathrooms' },
      // exteriors, plus the in-between parts of a house: stairs, halls, entries
      { key: 'architecture', label: 'Architecture' },
      { key: 'outdoor', label: 'Outdoor & gardens' },
      { key: 'objects', label: 'Furniture & objects' },
    ],
    posts: homeDesign as SavedPost[],
  },
];
